name: Deploy to S3
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Needed for OIDC
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build
        run: npm install && npm run build

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::195391091170:role/GithubS3Access #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Sync to S3
        run: aws s3 sync . s3://elijahcrainsite # Change this to your bucket name

      - name: Invalidate CloudFront (Optional)
        run: aws cloudfront create-invalidation --distribution-id your-cloudfront-id --paths "/*"