name: Deploy to S3
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # OIDC
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build
        run: bun install && bun run build

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Sync to S3
        run: aws s3 sync ./.next/ s3://elijahcrainsite --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id EAD7YE5HU5HKW --paths "/*"